import { generateTaskOutput } from "@/lib/ai/task-output";
import type { AiTaskType, BrandPromptContext } from "@/lib/ai/prompt-context";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const internalTenantId = "11111111-1111-4111-8111-111111111111";

type TaskRow = {
  id: string;
  tenant_id: string;
  brand_id: string;
  type: AiTaskType;
  title: string;
  prompt_context_json: BrandPromptContext;
};

export type ProcessQueuedAiTasksResult = {
  ok: boolean;
  processed: number;
  draftsCreated: number;
  recommendationsCreated: number;
  approvalsCreated: number;
  message: string;
};

export async function processQueuedAiTasks(tenantId = internalTenantId, limit = 25): Promise<ProcessQueuedAiTasksResult> {
  const supabase = createSupabaseAdminClient();

  if (!supabase) {
    return {
      ok: false,
      processed: 0,
      draftsCreated: 0,
      recommendationsCreated: 0,
      approvalsCreated: 0,
      message: "Supabase admin environment is not configured."
    };
  }

  const { data: tasks, error: taskError } = await supabase
    .from("ai_tasks")
    .select("id, tenant_id, brand_id, type, title, prompt_context_json")
    .eq("tenant_id", tenantId)
    .eq("status", "queued")
    .order("priority", { ascending: false })
    .order("created_at", { ascending: true })
    .limit(limit);

  if (taskError || !tasks) {
    return {
      ok: false,
      processed: 0,
      draftsCreated: 0,
      recommendationsCreated: 0,
      approvalsCreated: 0,
      message: taskError?.message ?? "Unable to load queued tasks."
    };
  }

  let processed = 0;
  let draftsCreated = 0;
  let recommendationsCreated = 0;
  let approvalsCreated = 0;

  for (const task of tasks as TaskRow[]) {
    const output = generateTaskOutput({
      taskId: task.id,
      taskType: task.type,
      taskTitle: task.title,
      tenantId: task.tenant_id,
      brandId: task.brand_id,
      promptContext: task.prompt_context_json
    });

    const { error: runningError } = await supabase
      .from("ai_tasks")
      .update({ status: "running", updated_at: new Date().toISOString() })
      .eq("id", task.id)
      .eq("status", "queued");

    if (runningError) {
      continue;
    }

    const createdDraftIds: string[] = [];
    const createdRecommendationIds: string[] = [];

    if (output.drafts.length > 0) {
      const { data, error } = await supabase.from("ai_drafts").insert(output.drafts).select("id, risk_level");

      if (error) {
        await supabase
          .from("ai_tasks")
          .update({ status: "failed", updated_at: new Date().toISOString() })
          .eq("id", task.id);
        continue;
      }

      createdDraftIds.push(...((data ?? []) as { id: string }[]).map((draft) => draft.id));
      draftsCreated += createdDraftIds.length;

      const approvals = ((data ?? []) as { id: string; risk_level: "low" | "medium" | "high" }[]).map((draft) => ({
        tenant_id: task.tenant_id,
        brand_id: task.brand_id,
        target_type: "ai_draft",
        target_id: draft.id,
        status: "pending",
        risk_level: draft.risk_level,
        notes: "Generated by Phase 1 AI operator foundation. Review required before publishing."
      }));

      if (approvals.length > 0) {
        const { error: approvalError } = await supabase.from("approvals").insert(approvals);
        if (!approvalError) {
          approvalsCreated += approvals.length;
        }
      }
    }

    if (output.recommendations.length > 0) {
      const { data, error } = await supabase.from("recommendations").insert(output.recommendations).select("id, risk_level");

      if (error) {
        await supabase
          .from("ai_tasks")
          .update({ status: "failed", updated_at: new Date().toISOString() })
          .eq("id", task.id);
        continue;
      }

      createdRecommendationIds.push(...((data ?? []) as { id: string }[]).map((recommendation) => recommendation.id));
      recommendationsCreated += createdRecommendationIds.length;

      const approvals = ((data ?? []) as { id: string; risk_level: "low" | "medium" | "high" }[]).map((recommendation) => ({
        tenant_id: task.tenant_id,
        brand_id: task.brand_id,
        target_type: "recommendation",
        target_id: recommendation.id,
        status: "pending",
        risk_level: recommendation.risk_level,
        notes: "Generated by Phase 1 AI operator foundation. Review required before action."
      }));

      if (approvals.length > 0) {
        const { error: approvalError } = await supabase.from("approvals").insert(approvals);
        if (!approvalError) {
          approvalsCreated += approvals.length;
        }
      }
    }

    await supabase.from("activity_logs").insert({
      tenant_id: task.tenant_id,
      brand_id: task.brand_id,
      actor_type: "system",
      action: "ai_task_processed",
      target_type: "ai_task",
      target_id: task.id,
      metadata_json: {
        createdDraftIds,
        createdRecommendationIds,
        generator: "phase1_deterministic_operator"
      }
    });

    await supabase
      .from("ai_tasks")
      .update({
        status: "completed",
        updated_at: new Date().toISOString()
      })
      .eq("id", task.id);

    processed += 1;
  }

  return {
    ok: true,
    processed,
    draftsCreated,
    recommendationsCreated,
    approvalsCreated,
    message: `Processed ${processed} queued AI tasks.`
  };
}
