import { generateTaskOutput } from "@/lib/ai/task-output";
import type { AiTaskType, BrandPromptContext } from "@/lib/ai/prompt-context";
import { queryPostgres } from "@/lib/db/postgres";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const internalTenantId = "11111111-1111-4111-8111-111111111111";

type TaskRow = {
  id: string;
  tenant_id: string;
  brand_id: string;
  type: AiTaskType;
  title: string;
  prompt_context_json: BrandPromptContext;
};

export type ProcessQueuedAiTasksResult = {
  ok: boolean;
  processed: number;
  draftsCreated: number;
  recommendationsCreated: number;
  approvalsCreated: number;
  message: string;
};

export async function processQueuedAiTasks(tenantId = internalTenantId, limit = 25): Promise<ProcessQueuedAiTasksResult> {
  const supabase = createSupabaseAdminClient();

  if (!supabase) {
    return processQueuedAiTasksWithPostgres(tenantId, limit);
  }

  const { data: tasks, error: taskError } = await supabase
    .from("ai_tasks")
    .select("id, tenant_id, brand_id, type, title, prompt_context_json")
    .eq("tenant_id", tenantId)
    .eq("status", "queued")
    .order("priority", { ascending: false })
    .order("created_at", { ascending: true })
    .limit(limit);

  if (taskError || !tasks) {
    return {
      ok: false,
      processed: 0,
      draftsCreated: 0,
      recommendationsCreated: 0,
      approvalsCreated: 0,
      message: taskError?.message ?? "Unable to load queued tasks."
    };
  }

  let processed = 0;
  let draftsCreated = 0;
  let recommendationsCreated = 0;
  let approvalsCreated = 0;

  for (const task of tasks as TaskRow[]) {
    const output = generateTaskOutput({
      taskId: task.id,
      taskType: task.type,
      taskTitle: task.title,
      tenantId: task.tenant_id,
      brandId: task.brand_id,
      promptContext: task.prompt_context_json
    });

    const { error: runningError } = await supabase
      .from("ai_tasks")
      .update({ status: "running", updated_at: new Date().toISOString() })
      .eq("id", task.id)
      .eq("status", "queued");

    if (runningError) {
      continue;
    }

    const createdDraftIds: string[] = [];
    const createdRecommendationIds: string[] = [];

    if (output.drafts.length > 0) {
      const { data, error } = await supabase.from("ai_drafts").insert(output.drafts).select("id, risk_level");

      if (error) {
        await supabase
          .from("ai_tasks")
          .update({ status: "failed", updated_at: new Date().toISOString() })
          .eq("id", task.id);
        continue;
      }

      createdDraftIds.push(...((data ?? []) as { id: string }[]).map((draft) => draft.id));
      draftsCreated += createdDraftIds.length;

      const approvals = ((data ?? []) as { id: string; risk_level: "low" | "medium" | "high" }[]).map((draft) => ({
        tenant_id: task.tenant_id,
        brand_id: task.brand_id,
        target_type: "ai_draft",
        target_id: draft.id,
        status: "pending",
        risk_level: draft.risk_level,
        notes: "Generated by Phase 1 AI operator foundation. Review required before publishing."
      }));

      if (approvals.length > 0) {
        const { error: approvalError } = await supabase.from("approvals").insert(approvals);
        if (!approvalError) {
          approvalsCreated += approvals.length;
        }
      }
    }

    if (output.recommendations.length > 0) {
      const { data, error } = await supabase.from("recommendations").insert(output.recommendations).select("id, risk_level");

      if (error) {
        await supabase
          .from("ai_tasks")
          .update({ status: "failed", updated_at: new Date().toISOString() })
          .eq("id", task.id);
        continue;
      }

      createdRecommendationIds.push(...((data ?? []) as { id: string }[]).map((recommendation) => recommendation.id));
      recommendationsCreated += createdRecommendationIds.length;

      const approvals = ((data ?? []) as { id: string; risk_level: "low" | "medium" | "high" }[]).map((recommendation) => ({
        tenant_id: task.tenant_id,
        brand_id: task.brand_id,
        target_type: "recommendation",
        target_id: recommendation.id,
        status: "pending",
        risk_level: recommendation.risk_level,
        notes: "Generated by Phase 1 AI operator foundation. Review required before action."
      }));

      if (approvals.length > 0) {
        const { error: approvalError } = await supabase.from("approvals").insert(approvals);
        if (!approvalError) {
          approvalsCreated += approvals.length;
        }
      }
    }

    await supabase.from("activity_logs").insert({
      tenant_id: task.tenant_id,
      brand_id: task.brand_id,
      actor_type: "system",
      action: "ai_task_processed",
      target_type: "ai_task",
      target_id: task.id,
      metadata_json: {
        createdDraftIds,
        createdRecommendationIds,
        generator: "phase1_deterministic_operator"
      }
    });

    await supabase
      .from("ai_tasks")
      .update({
        status: "completed",
        updated_at: new Date().toISOString()
      })
      .eq("id", task.id);

    processed += 1;
  }

  return {
    ok: true,
    processed,
    draftsCreated,
    recommendationsCreated,
    approvalsCreated,
    message: `Processed ${processed} queued AI tasks.`
  };
}

async function processQueuedAiTasksWithPostgres(tenantId = internalTenantId, limit = 25): Promise<ProcessQueuedAiTasksResult> {
  const taskResult = await queryPostgres<TaskRow>(
    `
    select id, tenant_id, brand_id, type, title, prompt_context_json
    from public.ai_tasks
    where tenant_id = $1 and status = 'queued'
    order by priority desc, created_at asc
    limit $2
    `,
    [tenantId, limit]
  );
  const tasks = taskResult?.rows ?? [];

  let processed = 0;
  let draftsCreated = 0;
  let recommendationsCreated = 0;
  let approvalsCreated = 0;

  for (const task of tasks) {
    const running = await queryPostgres(
      `
      update public.ai_tasks
      set status = 'running', updated_at = now()
      where id = $1 and status = 'queued'
      `,
      [task.id]
    );

    if ((running?.rowCount ?? 0) === 0) {
      continue;
    }

    const output = generateTaskOutput({
      taskId: task.id,
      taskType: task.type,
      taskTitle: task.title,
      tenantId: task.tenant_id,
      brandId: task.brand_id,
      promptContext: task.prompt_context_json
    });

    const createdDraftIds: string[] = [];
    const createdRecommendationIds: string[] = [];

    for (const draft of output.drafts) {
      const draftResult = await queryPostgres<{ id: string; risk_level: "low" | "medium" | "high" }>(
        `
        insert into public.ai_drafts (
          tenant_id,
          brand_id,
          ai_task_id,
          content_type,
          title,
          body,
          metadata_json,
          status,
          risk_level
        )
        values ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9)
        returning id, risk_level
        `,
        [
          draft.tenant_id,
          draft.brand_id,
          draft.ai_task_id,
          draft.content_type,
          draft.title,
          draft.body,
          JSON.stringify(draft.metadata_json),
          draft.status,
          draft.risk_level
        ]
      );
      const created = draftResult?.rows[0];
      if (!created) continue;

      createdDraftIds.push(created.id);
      draftsCreated += 1;

      await queryPostgres(
        `
        insert into public.approvals (tenant_id, brand_id, target_type, target_id, status, risk_level, notes)
        values ($1, $2, 'ai_draft', $3, 'pending', $4, 'Generated by Phase 1 AI operator foundation. Review required before publishing.')
        `,
        [draft.tenant_id, draft.brand_id, created.id, created.risk_level]
      );
      approvalsCreated += 1;
    }

    for (const recommendation of output.recommendations) {
      const recommendationResult = await queryPostgres<{ id: string; risk_level: "low" | "medium" | "high" }>(
        `
        insert into public.recommendations (
          tenant_id,
          brand_id,
          category,
          title,
          summary,
          rationale,
          suggested_action,
          impact_estimate,
          effort_estimate,
          risk_level,
          status,
          created_by
        )
        values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
        returning id, risk_level
        `,
        [
          recommendation.tenant_id,
          recommendation.brand_id,
          recommendation.category,
          recommendation.title,
          recommendation.summary,
          recommendation.rationale,
          recommendation.suggested_action,
          recommendation.impact_estimate,
          recommendation.effort_estimate,
          recommendation.risk_level,
          recommendation.status,
          recommendation.created_by
        ]
      );
      const created = recommendationResult?.rows[0];
      if (!created) continue;

      createdRecommendationIds.push(created.id);
      recommendationsCreated += 1;

      await queryPostgres(
        `
        insert into public.approvals (tenant_id, brand_id, target_type, target_id, status, risk_level, notes)
        values ($1, $2, 'recommendation', $3, 'pending', $4, 'Generated by Phase 1 AI operator foundation. Review required before action.')
        `,
        [recommendation.tenant_id, recommendation.brand_id, created.id, created.risk_level]
      );
      approvalsCreated += 1;
    }

    await queryPostgres(
      `
      insert into public.activity_logs (
        tenant_id,
        brand_id,
        actor_type,
        action,
        target_type,
        target_id,
        metadata_json
      )
      values ($1, $2, 'system', 'ai_task_processed', 'ai_task', $3, $4::jsonb)
      `,
      [
        task.tenant_id,
        task.brand_id,
        task.id,
        JSON.stringify({
          createdDraftIds,
          createdRecommendationIds,
          generator: "phase1_deterministic_operator"
        })
      ]
    );

    await queryPostgres(
      `
      update public.ai_tasks
      set status = 'completed', updated_at = now()
      where id = $1
      `,
      [task.id]
    );

    processed += 1;
  }

  return {
    ok: true,
    processed,
    draftsCreated,
    recommendationsCreated,
    approvalsCreated,
    message: `Processed ${processed} queued AI tasks.`
  };
}
